# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile_print_dialouge.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowIcon(QtGui.QIcon(":/icon/icon/group-48.ico"))
        Form.resize(790, 326)
        Form.setStyleSheet("QWidget{\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"}\n"
"QPushButton {\n"
"    font-family: \'Roboto \';\n"
"    color: white;\n"
"    text-align: left;\n"
"    height:20px;\n"
"    border: 1px;\n"
"    padding-left: 16px;\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: rgb(31, 149, 239); /* Normal background color */\n"
"    font-size: 18px; /* Set the font size here */\n"
"    /* Other styles */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45); /* Darker background color on hover */\n"
"    color: rgb(220, 220, 220); /* Slightly lighter text color on hover */\n"
"}\n"
"\n"
"QPushButton:checked {\n"
" \n"
"     background-color: rgb(45, 45, 45); /* Darker background color on checked */\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: \'Roboto \';\n"
"    color:rgb(24, 45, 83 );\n"
"font-size: 22px;\n"
"\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(18)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.addNewTest = QtWidgets.QPushButton(Form)
        self.addNewTest.setMinimumSize(QtCore.QSize(140, 40))
        self.addNewTest.setMaximumSize(QtCore.QSize(140, 40))
        self.addNewTest.setObjectName("addNewTest")
        self.horizontalLayout_7.addWidget(self.addNewTest)
        spacerItem = QtWidgets.QSpacerItem(550, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.stress_label_2 = QtWidgets.QLabel(Form)
        self.stress_label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.stress_label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.stress_label_2.setObjectName("stress_label_2")
        self.horizontalLayout_8.addWidget(self.stress_label_2)
        spacerItem2 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stress_label = QtWidgets.QLabel(Form)
        self.stress_label.setMinimumSize(QtCore.QSize(250, 30))
        self.stress_label.setMaximumSize(QtCore.QSize(250, 30))
        self.stress_label.setObjectName("stress_label")
        self.horizontalLayout_4.addWidget(self.stress_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stress_comboBox = QtWidgets.QComboBox(Form)
        self.stress_comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.stress_comboBox.setMaximumSize(QtCore.QSize(100, 30))
        self.stress_comboBox.setObjectName("stress_comboBox")
        self.horizontalLayout_3.addWidget(self.stress_comboBox)
        self.stress_viewscore = QtWidgets.QPushButton(Form)
        self.stress_viewscore.setMinimumSize(QtCore.QSize(120, 40))
        self.stress_viewscore.setMaximumSize(QtCore.QSize(120, 40))
        self.stress_viewscore.setObjectName("stress_viewscore")
        self.horizontalLayout_3.addWidget(self.stress_viewscore)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.stress_compare = QtWidgets.QPushButton(Form)
        self.stress_compare.setMinimumSize(QtCore.QSize(100, 40))
        self.stress_compare.setMaximumSize(QtCore.QSize(100, 40))
        self.stress_compare.setObjectName("stress_compare")
        self.horizontalLayout_4.addWidget(self.stress_compare)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.depression_label = QtWidgets.QLabel(Form)
        self.depression_label.setMinimumSize(QtCore.QSize(250, 30))
        self.depression_label.setMaximumSize(QtCore.QSize(250, 30))
        self.depression_label.setObjectName("depression_label")
        self.horizontalLayout_5.addWidget(self.depression_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.depression_comboBox = QtWidgets.QComboBox(Form)
        self.depression_comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.depression_comboBox.setMaximumSize(QtCore.QSize(100, 30))
        self.depression_comboBox.setObjectName("depression_comboBox")
        self.horizontalLayout_2.addWidget(self.depression_comboBox)
        self.depression_viewscore = QtWidgets.QPushButton(Form)
        self.depression_viewscore.setMinimumSize(QtCore.QSize(120, 40))
        self.depression_viewscore.setMaximumSize(QtCore.QSize(120, 40))
        self.depression_viewscore.setObjectName("depression_viewscore")
        self.horizontalLayout_2.addWidget(self.depression_viewscore)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.depression_compare = QtWidgets.QPushButton(Form)
        self.depression_compare.setMinimumSize(QtCore.QSize(100, 40))
        self.depression_compare.setMaximumSize(QtCore.QSize(100, 40))
        self.depression_compare.setObjectName("depression_compare")
        self.horizontalLayout_5.addWidget(self.depression_compare)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.self_esteem_label = QtWidgets.QLabel(Form)
        self.self_esteem_label.setMinimumSize(QtCore.QSize(250, 30))
        self.self_esteem_label.setMaximumSize(QtCore.QSize(250, 30))
        self.self_esteem_label.setObjectName("self_esteem_label")
        self.horizontalLayout_6.addWidget(self.self_esteem_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selfesteem_comboBox = QtWidgets.QComboBox(Form)
        self.selfesteem_comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.selfesteem_comboBox.setMaximumSize(QtCore.QSize(100, 30))
        self.selfesteem_comboBox.setObjectName("selfesteem_comboBox")
        self.horizontalLayout.addWidget(self.selfesteem_comboBox)
        self.selfesteem_viewscore = QtWidgets.QPushButton(Form)
        self.selfesteem_viewscore.setMinimumSize(QtCore.QSize(120, 40))
        self.selfesteem_viewscore.setMaximumSize(QtCore.QSize(120, 40))
        self.selfesteem_viewscore.setObjectName("selfesteem_viewscore")
        self.horizontalLayout.addWidget(self.selfesteem_viewscore)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.selfesteem_compare = QtWidgets.QPushButton(Form)
        self.selfesteem_compare.setMinimumSize(QtCore.QSize(100, 40))
        self.selfesteem_compare.setMaximumSize(QtCore.QSize(100, 40))
        self.selfesteem_compare.setObjectName("selfesteem_compare")
        self.horizontalLayout_6.addWidget(self.selfesteem_compare)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addNewTest.setText(_translate("Form", "Add new Test"))
        self.stress_label_2.setText(_translate("Form", "date"))
        self.stress_label.setText(_translate("Form", "Stress Test Scores"))
        self.stress_viewscore.setText(_translate("Form", "View Score"))
        self.stress_compare.setText(_translate("Form", "Compare"))
        self.depression_label.setText(_translate("Form", "Depression Test Scores"))
        self.depression_viewscore.setText(_translate("Form", "View Score"))
        self.depression_compare.setText(_translate("Form", "Compare"))
        self.self_esteem_label.setText(_translate("Form", "Self Esteem Test Scores"))
        self.selfesteem_viewscore.setText(_translate("Form", "View Score"))
        self.selfesteem_compare.setText(_translate("Form", "Compare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
