from PyQt5 import QtCore, QtGui, QtWidgets        



class StressTab:
    def __init__(self, parent, stackedWidget):
        self.stackedWidget = stackedWidget
        self.setupStressPage(parent)
        

    def setupStressPage(self, parent):
        self.Stress_Page = QtWidgets.QWidget()
        self.Stress_Page.setObjectName("Stress_Page")
        self.Stress_Page_gridLayout = QtWidgets.QGridLayout(self.Stress_Page)
        self.Stress_Page_gridLayout.setObjectName("Stress_Page_gridLayout")
        self.Stress_tabWidget = QtWidgets.QTabWidget(self.Stress_Page)
        font = QtGui.QFont()
        font.setFamily("Roboto Cn")
        font.setPointSize(11)
        self.Stress_tabWidget.setFont(font)
        self.Stress_tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    /* The tab widget frame */\n"
"    border-top: 2px solid rgb(31, 149, 239);\n"
"    border-radius: 5px; /* Rounded corners for the pane */\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    /* The tab bar */\n"
"    left: 5px; /* Move the bar to the right */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* The tab */\n"
"    background-color: rgb(31, 149, 239);\n"
"    color: white;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    min-width: 80px; /* Set the minimum width of the tab */\n"
"    min-height: 30px; /* Set the minimum height of the tab */\n"
"    margin-right: 2px; /* Space between tabs */\n"
"    border-top-left-radius: 5px; /* Rounded top-left corner */\n"
"    border-top-right-radius: 5px; /* Rounded top-right corner */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    /* The selected tab */\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-top-left-radius: 5px; /* Maintain rounded corner when selected */\n"
"    border-top-right-radius: 5px; /* Maintain rounded corner when selected */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    /* The tab when hovered over */\n"
"    background-color: rgb(51, 169, 259);\n"
"}\n"
"")
        self.Stress_tabWidget.setObjectName("Stress_tabWidget")
        self.ST_Tab = QtWidgets.QWidget()
        self.ST_Tab.setStyleSheet("QLabel {\n"
"\n"
" \n"
"   \n"
"    \n"
"}\n"
"")
        self.ST_Tab.setObjectName("ST_Tab")
        self.ST_Tab_gridLayout = QtWidgets.QGridLayout(self.ST_Tab)
        self.ST_Tab_gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.ST_Tab_gridLayout.setObjectName("ST_Tab_gridLayout")
        self.ST_widget = QtWidgets.QWidget(self.ST_Tab)
        self.ST_widget.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    text-align:center;\n"
"    height:70px;\n"
"    border: 1px;\n"
"  \n"
"    border-radius: 8px; /* Round top left corner */\n"
"    \n"
"    background-color: rgb(31, 149, 239); /* Normal background color */\n"
"    font-size: 35px; /* Set the font size here */\n"
"    /* Other styles */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(45, 45, 45); /* Darker background color on hover */\n"
"    color: rgb(220, 220, 220); /* Slightly lighter text color on hover */\n"
"}\n"
"\n"
"QPushButton:checked {\n"
" \n"
"     background-color: rgb(45, 45, 45); /* Darker background color on checked */\n"
"}")
        self.ST_widget.setObjectName("ST_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ST_widget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ST_Q1_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q1_horizontal_question_lyt.setObjectName("ST_Q1_horizontal_question_lyt")
        self.ST_Q1 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q1.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q1.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q1.setFont(font)
        self.ST_Q1.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q1.setObjectName("ST_Q1")
        self.ST_Q1_horizontal_question_lyt.addWidget(self.ST_Q1)
        spacerItem69 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q1_horizontal_question_lyt.addItem(spacerItem69)
        self.ST_Q1_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q1_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q1_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q1_Label.setFont(font)
        self.ST_Q1_Label.setObjectName("ST_Q1_Label")
        self.ST_Q1_horizontal_question_lyt.addWidget(self.ST_Q1_Label)
        spacerItem70 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q1_horizontal_question_lyt.addItem(spacerItem70)
        self.ST_Q1_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q1_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q1_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q1_horizontal_selection_lyt.setObjectName("ST_Q1_horizontal_selection_lyt")
        self.ST_1_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_1_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_1.setCheckable(True)
        self.ST_1_pushButton_1.setAutoExclusive(True)
        self.ST_1_pushButton_1.setObjectName("ST_1_pushButton_1")
        self.ST_Q1_horizontal_selection_lyt.addWidget(self.ST_1_pushButton_1)
        self.ST_1_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_1_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_2.setCheckable(True)
        self.ST_1_pushButton_2.setAutoExclusive(True)
        self.ST_1_pushButton_2.setObjectName("ST_1_pushButton_2")
        self.ST_Q1_horizontal_selection_lyt.addWidget(self.ST_1_pushButton_2)
        self.ST_1_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_1_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_3.setCheckable(True)
        self.ST_1_pushButton_3.setAutoExclusive(True)
        self.ST_1_pushButton_3.setObjectName("ST_1_pushButton_3")
        self.ST_Q1_horizontal_selection_lyt.addWidget(self.ST_1_pushButton_3)
        self.ST_1_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_1_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_4.setCheckable(True)
        self.ST_1_pushButton_4.setAutoExclusive(True)
        self.ST_1_pushButton_4.setObjectName("ST_1_pushButton_4")
        self.ST_Q1_horizontal_selection_lyt.addWidget(self.ST_1_pushButton_4)
        self.ST_1_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_1_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_1_pushButton_5.setCheckable(True)
        self.ST_1_pushButton_5.setAutoExclusive(True)
        self.ST_1_pushButton_5.setObjectName("ST_1_pushButton_5")
        self.ST_Q1_horizontal_selection_lyt.addWidget(self.ST_1_pushButton_5)
        self.ST_Q1_horizontal_question_lyt.addLayout(self.ST_Q1_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q1_horizontal_question_lyt)
        self.ST_Q2_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q2_horizontal_question_lyt.setObjectName("ST_Q2_horizontal_question_lyt")
        self.ST_Q2 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q2.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q2.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q2.setFont(font)
        self.ST_Q2.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q2.setObjectName("ST_Q2")
        self.ST_Q2_horizontal_question_lyt.addWidget(self.ST_Q2)
        spacerItem71 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q2_horizontal_question_lyt.addItem(spacerItem71)
        self.ST_Q2_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q2_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q2_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q2_Label.setFont(font)
        self.ST_Q2_Label.setObjectName("ST_Q2_Label")
        self.ST_Q2_horizontal_question_lyt.addWidget(self.ST_Q2_Label)
        spacerItem72 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q2_horizontal_question_lyt.addItem(spacerItem72)
        self.ST_Q2_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q2_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q2_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q2_horizontal_selection_lyt.setObjectName("ST_Q2_horizontal_selection_lyt")
        self.ST_2_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_2_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_1.setCheckable(True)
        self.ST_2_pushButton_1.setAutoExclusive(True)
        self.ST_2_pushButton_1.setObjectName("ST_2_pushButton_1")
        self.ST_Q2_horizontal_selection_lyt.addWidget(self.ST_2_pushButton_1)
        self.ST_2_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_2_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_2.setCheckable(True)
        self.ST_2_pushButton_2.setAutoExclusive(True)
        self.ST_2_pushButton_2.setObjectName("ST_2_pushButton_2")
        self.ST_Q2_horizontal_selection_lyt.addWidget(self.ST_2_pushButton_2)
        self.ST_2_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_2_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_3.setCheckable(True)
        self.ST_2_pushButton_3.setAutoExclusive(True)
        self.ST_2_pushButton_3.setObjectName("ST_2_pushButton_3")
        self.ST_Q2_horizontal_selection_lyt.addWidget(self.ST_2_pushButton_3)
        self.ST_2_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_2_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_4.setCheckable(True)
        self.ST_2_pushButton_4.setAutoExclusive(True)
        self.ST_2_pushButton_4.setObjectName("ST_2_pushButton_4")
        self.ST_Q2_horizontal_selection_lyt.addWidget(self.ST_2_pushButton_4)
        self.ST_2_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_2_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_2_pushButton_5.setCheckable(True)
        self.ST_2_pushButton_5.setAutoExclusive(True)
        self.ST_2_pushButton_5.setObjectName("ST_2_pushButton_5")
        self.ST_Q2_horizontal_selection_lyt.addWidget(self.ST_2_pushButton_5)
        self.ST_Q2_horizontal_question_lyt.addLayout(self.ST_Q2_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q2_horizontal_question_lyt)
        self.ST_Q3_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q3_horizontal_question_lyt.setObjectName("ST_Q3_horizontal_question_lyt")
        self.ST_Q3 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q3.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q3.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q3.setFont(font)
        self.ST_Q3.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q3.setObjectName("ST_Q3")
        self.ST_Q3_horizontal_question_lyt.addWidget(self.ST_Q3)
        spacerItem73 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q3_horizontal_question_lyt.addItem(spacerItem73)
        self.ST_Q3_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q3_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q3_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q3_Label.setFont(font)
        self.ST_Q3_Label.setObjectName("ST_Q3_Label")
        self.ST_Q3_horizontal_question_lyt.addWidget(self.ST_Q3_Label)
        spacerItem74 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q3_horizontal_question_lyt.addItem(spacerItem74)
        self.ST_Q3_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q3_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q3_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q3_horizontal_selection_lyt.setObjectName("ST_Q3_horizontal_selection_lyt")
        self.ST_3_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_3_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_1.setCheckable(True)
        self.ST_3_pushButton_1.setAutoExclusive(True)
        self.ST_3_pushButton_1.setObjectName("ST_3_pushButton_1")
        self.ST_Q3_horizontal_selection_lyt.addWidget(self.ST_3_pushButton_1)
        self.ST_3_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_3_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_2.setCheckable(True)
        self.ST_3_pushButton_2.setAutoExclusive(True)
        self.ST_3_pushButton_2.setObjectName("ST_3_pushButton_2")
        self.ST_Q3_horizontal_selection_lyt.addWidget(self.ST_3_pushButton_2)
        self.ST_3_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_3_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_3.setCheckable(True)
        self.ST_3_pushButton_3.setAutoExclusive(True)
        self.ST_3_pushButton_3.setObjectName("ST_3_pushButton_3")
        self.ST_Q3_horizontal_selection_lyt.addWidget(self.ST_3_pushButton_3)
        self.ST_3_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_3_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_4.setCheckable(True)
        self.ST_3_pushButton_4.setAutoExclusive(True)
        self.ST_3_pushButton_4.setObjectName("ST_3_pushButton_4")
        self.ST_Q3_horizontal_selection_lyt.addWidget(self.ST_3_pushButton_4)
        self.ST_3_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_3_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_3_pushButton_5.setCheckable(True)
        self.ST_3_pushButton_5.setAutoExclusive(True)
        self.ST_3_pushButton_5.setObjectName("ST_3_pushButton_5")
        self.ST_Q3_horizontal_selection_lyt.addWidget(self.ST_3_pushButton_5)
        self.ST_Q3_horizontal_question_lyt.addLayout(self.ST_Q3_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q3_horizontal_question_lyt)
        self.ST_Q4_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q4_horizontal_question_lyt.setObjectName("ST_Q4_horizontal_question_lyt")
        self.ST_Q4 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q4.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q4.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q4.setFont(font)
        self.ST_Q4.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q4.setObjectName("ST_Q4")
        self.ST_Q4_horizontal_question_lyt.addWidget(self.ST_Q4)
        spacerItem75 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q4_horizontal_question_lyt.addItem(spacerItem75)
        self.ST_Q4_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q4_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q4_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q4_Label.setFont(font)
        self.ST_Q4_Label.setObjectName("ST_Q4_Label")
        self.ST_Q4_horizontal_question_lyt.addWidget(self.ST_Q4_Label)
        spacerItem76 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q4_horizontal_question_lyt.addItem(spacerItem76)
        self.ST_Q4_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q4_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q4_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q4_horizontal_selection_lyt.setObjectName("ST_Q4_horizontal_selection_lyt")
        self.ST_4_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_4_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_1.setCheckable(True)
        self.ST_4_pushButton_1.setAutoExclusive(True)
        self.ST_4_pushButton_1.setObjectName("ST_4_pushButton_1")
        self.ST_Q4_horizontal_selection_lyt.addWidget(self.ST_4_pushButton_1)
        self.ST_4_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_4_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_2.setCheckable(True)
        self.ST_4_pushButton_2.setAutoExclusive(True)
        self.ST_4_pushButton_2.setObjectName("ST_4_pushButton_2")
        self.ST_Q4_horizontal_selection_lyt.addWidget(self.ST_4_pushButton_2)
        self.ST_4_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_4_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_3.setCheckable(True)
        self.ST_4_pushButton_3.setAutoExclusive(True)
        self.ST_4_pushButton_3.setObjectName("ST_4_pushButton_3")
        self.ST_Q4_horizontal_selection_lyt.addWidget(self.ST_4_pushButton_3)
        self.ST_4_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_4_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_4.setCheckable(True)
        self.ST_4_pushButton_4.setAutoExclusive(True)
        self.ST_4_pushButton_4.setObjectName("ST_4_pushButton_4")
        self.ST_Q4_horizontal_selection_lyt.addWidget(self.ST_4_pushButton_4)
        self.ST_4_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_4_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_4_pushButton_5.setCheckable(True)
        self.ST_4_pushButton_5.setAutoExclusive(True)
        self.ST_4_pushButton_5.setObjectName("ST_4_pushButton_5")
        self.ST_Q4_horizontal_selection_lyt.addWidget(self.ST_4_pushButton_5)
        self.ST_Q4_horizontal_question_lyt.addLayout(self.ST_Q4_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q4_horizontal_question_lyt)
        self.ST_Q5_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q5_horizontal_question_lyt.setObjectName("ST_Q5_horizontal_question_lyt")
        self.ST_Q5 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q5.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q5.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q5.setFont(font)
        self.ST_Q5.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q5.setObjectName("ST_Q5")
        self.ST_Q5_horizontal_question_lyt.addWidget(self.ST_Q5)
        spacerItem77 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q5_horizontal_question_lyt.addItem(spacerItem77)
        self.ST_Q5_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q5_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q5_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q5_Label.setFont(font)
        self.ST_Q5_Label.setObjectName("ST_Q5_Label")
        self.ST_Q5_horizontal_question_lyt.addWidget(self.ST_Q5_Label)
        spacerItem78 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q5_horizontal_question_lyt.addItem(spacerItem78)
        self.ST_Q5_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q5_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q5_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q5_horizontal_selection_lyt.setObjectName("ST_Q5_horizontal_selection_lyt")
        self.ST_5_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_5_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_1.setCheckable(True)
        self.ST_5_pushButton_1.setAutoExclusive(True)
        self.ST_5_pushButton_1.setObjectName("ST_5_pushButton_1")
        self.ST_Q5_horizontal_selection_lyt.addWidget(self.ST_5_pushButton_1)
        self.ST_5_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_5_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_2.setCheckable(True)
        self.ST_5_pushButton_2.setAutoExclusive(True)
        self.ST_5_pushButton_2.setObjectName("ST_5_pushButton_2")
        self.ST_Q5_horizontal_selection_lyt.addWidget(self.ST_5_pushButton_2)
        self.ST_5_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_5_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_3.setCheckable(True)
        self.ST_5_pushButton_3.setAutoExclusive(True)
        self.ST_5_pushButton_3.setObjectName("ST_5_pushButton_3")
        self.ST_Q5_horizontal_selection_lyt.addWidget(self.ST_5_pushButton_3)
        self.ST_5_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_5_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_4.setCheckable(True)
        self.ST_5_pushButton_4.setAutoExclusive(True)
        self.ST_5_pushButton_4.setObjectName("ST_5_pushButton_4")
        self.ST_Q5_horizontal_selection_lyt.addWidget(self.ST_5_pushButton_4)
        self.ST_5_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_5_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_5_pushButton_5.setCheckable(True)
        self.ST_5_pushButton_5.setAutoExclusive(True)
        self.ST_5_pushButton_5.setObjectName("ST_5_pushButton_5")
        self.ST_Q5_horizontal_selection_lyt.addWidget(self.ST_5_pushButton_5)
        self.ST_Q5_horizontal_question_lyt.addLayout(self.ST_Q5_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q5_horizontal_question_lyt)
        self.ST_Q6_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q6_horizontal_question_lyt.setObjectName("ST_Q6_horizontal_question_lyt")
        self.ST_Q6 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q6.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q6.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q6.setFont(font)
        self.ST_Q6.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q6.setObjectName("ST_Q6")
        self.ST_Q6_horizontal_question_lyt.addWidget(self.ST_Q6)
        spacerItem79 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q6_horizontal_question_lyt.addItem(spacerItem79)
        self.ST_Q6_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q6_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q6_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q6_Label.setFont(font)
        self.ST_Q6_Label.setObjectName("ST_Q6_Label")
        self.ST_Q6_horizontal_question_lyt.addWidget(self.ST_Q6_Label)
        spacerItem80 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q6_horizontal_question_lyt.addItem(spacerItem80)
        self.ST_Q6_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q6_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q6_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q6_horizontal_selection_lyt.setObjectName("ST_Q6_horizontal_selection_lyt")
        self.ST_6_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_6_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_1.setCheckable(True)
        self.ST_6_pushButton_1.setAutoExclusive(True)
        self.ST_6_pushButton_1.setObjectName("ST_6_pushButton_1")
        self.ST_Q6_horizontal_selection_lyt.addWidget(self.ST_6_pushButton_1)
        self.ST_6_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_6_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_2.setCheckable(True)
        self.ST_6_pushButton_2.setAutoExclusive(True)
        self.ST_6_pushButton_2.setObjectName("ST_6_pushButton_2")
        self.ST_Q6_horizontal_selection_lyt.addWidget(self.ST_6_pushButton_2)
        self.ST_6_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_6_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_3.setCheckable(True)
        self.ST_6_pushButton_3.setAutoExclusive(True)
        self.ST_6_pushButton_3.setObjectName("ST_6_pushButton_3")
        self.ST_Q6_horizontal_selection_lyt.addWidget(self.ST_6_pushButton_3)
        self.ST_6_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_6_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_4.setCheckable(True)
        self.ST_6_pushButton_4.setAutoExclusive(True)
        self.ST_6_pushButton_4.setObjectName("ST_6_pushButton_4")
        self.ST_Q6_horizontal_selection_lyt.addWidget(self.ST_6_pushButton_4)
        self.ST_6_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_6_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_6_pushButton_5.setCheckable(True)
        self.ST_6_pushButton_5.setAutoExclusive(True)
        self.ST_6_pushButton_5.setObjectName("ST_6_pushButton_5")
        self.ST_Q6_horizontal_selection_lyt.addWidget(self.ST_6_pushButton_5)
        self.ST_Q6_horizontal_question_lyt.addLayout(self.ST_Q6_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q6_horizontal_question_lyt)
        self.ST_Q7_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q7_horizontal_question_lyt.setObjectName("ST_Q7_horizontal_question_lyt")
        self.ST_Q7 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q7.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q7.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q7.setFont(font)
        self.ST_Q7.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q7.setObjectName("ST_Q7")
        self.ST_Q7_horizontal_question_lyt.addWidget(self.ST_Q7)
        spacerItem81 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q7_horizontal_question_lyt.addItem(spacerItem81)
        self.ST_Q7_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q7_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q7_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q7_Label.setFont(font)
        self.ST_Q7_Label.setObjectName("ST_Q7_Label")
        self.ST_Q7_horizontal_question_lyt.addWidget(self.ST_Q7_Label)
        spacerItem82 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q7_horizontal_question_lyt.addItem(spacerItem82)
        self.ST_Q7_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q7_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q7_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q7_horizontal_selection_lyt.setObjectName("ST_Q7_horizontal_selection_lyt")
        self.ST_7_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_7_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_1.setCheckable(True)
        self.ST_7_pushButton_1.setAutoExclusive(True)
        self.ST_7_pushButton_1.setObjectName("ST_7_pushButton_1")
        self.ST_Q7_horizontal_selection_lyt.addWidget(self.ST_7_pushButton_1)
        self.ST_7_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_7_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_2.setCheckable(True)
        self.ST_7_pushButton_2.setAutoExclusive(True)
        self.ST_7_pushButton_2.setObjectName("ST_7_pushButton_2")
        self.ST_Q7_horizontal_selection_lyt.addWidget(self.ST_7_pushButton_2)
        self.ST_7_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_7_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_3.setCheckable(True)
        self.ST_7_pushButton_3.setAutoExclusive(True)
        self.ST_7_pushButton_3.setObjectName("ST_7_pushButton_3")
        self.ST_Q7_horizontal_selection_lyt.addWidget(self.ST_7_pushButton_3)
        self.ST_7_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_7_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_4.setCheckable(True)
        self.ST_7_pushButton_4.setAutoExclusive(True)
        self.ST_7_pushButton_4.setObjectName("ST_7_pushButton_4")
        self.ST_Q7_horizontal_selection_lyt.addWidget(self.ST_7_pushButton_4)
        self.ST_7_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_7_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_7_pushButton_5.setCheckable(True)
        self.ST_7_pushButton_5.setAutoExclusive(True)
        self.ST_7_pushButton_5.setObjectName("ST_7_pushButton_5")
        self.ST_Q7_horizontal_selection_lyt.addWidget(self.ST_7_pushButton_5)
        self.ST_Q7_horizontal_question_lyt.addLayout(self.ST_Q7_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q7_horizontal_question_lyt)
        self.ST_Q8_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q8_horizontal_question_lyt.setObjectName("ST_Q8_horizontal_question_lyt")
        self.ST_Q8 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q8.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q8.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q8.setFont(font)
        self.ST_Q8.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q8.setObjectName("ST_Q8")
        self.ST_Q8_horizontal_question_lyt.addWidget(self.ST_Q8)
        spacerItem83 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q8_horizontal_question_lyt.addItem(spacerItem83)
        self.ST_Q8_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q8_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q8_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q8_Label.setFont(font)
        self.ST_Q8_Label.setObjectName("ST_Q8_Label")
        self.ST_Q8_horizontal_question_lyt.addWidget(self.ST_Q8_Label)
        spacerItem84 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q8_horizontal_question_lyt.addItem(spacerItem84)
        self.ST_Q8_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q8_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q8_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q8_horizontal_selection_lyt.setObjectName("ST_Q8_horizontal_selection_lyt")
        self.ST_8_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_8_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_1.setCheckable(True)
        self.ST_8_pushButton_1.setAutoExclusive(True)
        self.ST_8_pushButton_1.setObjectName("ST_8_pushButton_1")
        self.ST_Q8_horizontal_selection_lyt.addWidget(self.ST_8_pushButton_1)
        self.ST_8_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_8_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_2.setCheckable(True)
        self.ST_8_pushButton_2.setAutoExclusive(True)
        self.ST_8_pushButton_2.setObjectName("ST_8_pushButton_2")
        self.ST_Q8_horizontal_selection_lyt.addWidget(self.ST_8_pushButton_2)
        self.ST_8_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_8_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_3.setCheckable(True)
        self.ST_8_pushButton_3.setAutoExclusive(True)
        self.ST_8_pushButton_3.setObjectName("ST_8_pushButton_3")
        self.ST_Q8_horizontal_selection_lyt.addWidget(self.ST_8_pushButton_3)
        self.ST_8_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_8_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_4.setCheckable(True)
        self.ST_8_pushButton_4.setAutoExclusive(True)
        self.ST_8_pushButton_4.setObjectName("ST_8_pushButton_4")
        self.ST_Q8_horizontal_selection_lyt.addWidget(self.ST_8_pushButton_4)
        self.ST_8_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_8_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_8_pushButton_5.setCheckable(True)
        self.ST_8_pushButton_5.setAutoExclusive(True)
        self.ST_8_pushButton_5.setObjectName("ST_8_pushButton_5")
        self.ST_Q8_horizontal_selection_lyt.addWidget(self.ST_8_pushButton_5)
        self.ST_Q8_horizontal_question_lyt.addLayout(self.ST_Q8_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q8_horizontal_question_lyt)
        self.ST_Q9_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q9_horizontal_question_lyt.setObjectName("ST_Q9_horizontal_question_lyt")
        self.ST_Q9 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q9.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q9.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q9.setFont(font)
        self.ST_Q9.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q9.setObjectName("ST_Q9")
        self.ST_Q9_horizontal_question_lyt.addWidget(self.ST_Q9)
        spacerItem85 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q9_horizontal_question_lyt.addItem(spacerItem85)
        self.ST_Q9_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q9_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q9_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.ST_Q9_Label.setFont(font)
        self.ST_Q9_Label.setObjectName("ST_Q9_Label")
        self.ST_Q9_horizontal_question_lyt.addWidget(self.ST_Q9_Label)
        spacerItem86 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q9_horizontal_question_lyt.addItem(spacerItem86)
        self.ST_Q9_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q9_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q9_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q9_horizontal_selection_lyt.setObjectName("ST_Q9_horizontal_selection_lyt")
        self.ST_9_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_9_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_1.setCheckable(True)
        self.ST_9_pushButton_1.setAutoExclusive(True)
        self.ST_9_pushButton_1.setObjectName("ST_9_pushButton_1")
        self.ST_Q9_horizontal_selection_lyt.addWidget(self.ST_9_pushButton_1)
        self.ST_9_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_9_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_2.setCheckable(True)
        self.ST_9_pushButton_2.setAutoExclusive(True)
        self.ST_9_pushButton_2.setObjectName("ST_9_pushButton_2")
        self.ST_Q9_horizontal_selection_lyt.addWidget(self.ST_9_pushButton_2)
        self.ST_9_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_9_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_3.setCheckable(True)
        self.ST_9_pushButton_3.setAutoExclusive(True)
        self.ST_9_pushButton_3.setObjectName("ST_9_pushButton_3")
        self.ST_Q9_horizontal_selection_lyt.addWidget(self.ST_9_pushButton_3)
        self.ST_9_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_9_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_4.setCheckable(True)
        self.ST_9_pushButton_4.setAutoExclusive(True)
        self.ST_9_pushButton_4.setObjectName("ST_9_pushButton_4")
        self.ST_Q9_horizontal_selection_lyt.addWidget(self.ST_9_pushButton_4)
        self.ST_9_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_9_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_9_pushButton_5.setCheckable(True)
        self.ST_9_pushButton_5.setAutoExclusive(True)
        self.ST_9_pushButton_5.setObjectName("ST_9_pushButton_5")
        self.ST_Q9_horizontal_selection_lyt.addWidget(self.ST_9_pushButton_5)
        self.ST_Q9_horizontal_question_lyt.addLayout(self.ST_Q9_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q9_horizontal_question_lyt)
        self.ST_Q10_horizontal_question_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q10_horizontal_question_lyt.setObjectName("ST_Q10_horizontal_question_lyt")
        self.ST_Q10 = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q10.setMinimumSize(QtCore.QSize(60, 60))
        self.ST_Q10.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Roboto Bk")
        font.setPointSize(14)
        self.ST_Q10.setFont(font)
        self.ST_Q10.setStyleSheet("QLabel {\n"
"     color: rgb(31, 149, 239);\n"
"    qproperty-alignment: AlignCenter;\n"
"   \n"
"    border: 3px solid rgb(31, 149, 239); /* This adds a 1px solid white border around the QLabel */\n"
"    border-radius: 10px; /* Optional: if you want rounded corners */\n"
"}\n"
"")
        self.ST_Q10.setObjectName("ST_Q10")
        self.ST_Q10_horizontal_question_lyt.addWidget(self.ST_Q10)
        spacerItem87 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q10_horizontal_question_lyt.addItem(spacerItem87)
        self.ST_Q10_Label = QtWidgets.QLabel(self.ST_widget)
        self.ST_Q10_Label.setMinimumSize(QtCore.QSize(825, 50))
        self.ST_Q10_Label.setMaximumSize(QtCore.QSize(825, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.ST_Q10_Label.setFont(font)
        self.ST_Q10_Label.setObjectName("ST_Q10_Label")
        self.ST_Q10_horizontal_question_lyt.addWidget(self.ST_Q10_Label)
        spacerItem88 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.ST_Q10_horizontal_question_lyt.addItem(spacerItem88)
        self.ST_Q10_horizontal_selection_lyt = QtWidgets.QHBoxLayout()
        self.ST_Q10_horizontal_selection_lyt.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ST_Q10_horizontal_selection_lyt.setSpacing(20)
        self.ST_Q10_horizontal_selection_lyt.setObjectName("ST_Q10_horizontal_selection_lyt")
        self.ST_10_pushButton_1 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_10_pushButton_1.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_1.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_1.setCheckable(True)
        self.ST_10_pushButton_1.setAutoExclusive(True)
        self.ST_10_pushButton_1.setObjectName("ST_10_pushButton_1")
        self.ST_Q10_horizontal_selection_lyt.addWidget(self.ST_10_pushButton_1)
        self.ST_10_pushButton_2 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_10_pushButton_2.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_2.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_2.setCheckable(True)
        self.ST_10_pushButton_2.setAutoExclusive(True)
        self.ST_10_pushButton_2.setObjectName("ST_10_pushButton_2")
        self.ST_Q10_horizontal_selection_lyt.addWidget(self.ST_10_pushButton_2)
        self.ST_10_pushButton_3 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_10_pushButton_3.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_3.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_3.setCheckable(True)
        self.ST_10_pushButton_3.setAutoExclusive(True)
        self.ST_10_pushButton_3.setObjectName("ST_10_pushButton_3")
        self.ST_Q10_horizontal_selection_lyt.addWidget(self.ST_10_pushButton_3)
        self.ST_10_pushButton_4 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_10_pushButton_4.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_4.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_4.setCheckable(True)
        self.ST_10_pushButton_4.setAutoExclusive(True)
        self.ST_10_pushButton_4.setObjectName("ST_10_pushButton_4")
        self.ST_Q10_horizontal_selection_lyt.addWidget(self.ST_10_pushButton_4)
        self.ST_10_pushButton_5 = QtWidgets.QPushButton(self.ST_widget)
        self.ST_10_pushButton_5.setMinimumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_5.setMaximumSize(QtCore.QSize(60, 55))
        self.ST_10_pushButton_5.setCheckable(True)
        self.ST_10_pushButton_5.setAutoExclusive(True)
        self.ST_10_pushButton_5.setObjectName("ST_10_pushButton_5")
        self.ST_Q10_horizontal_selection_lyt.addWidget(self.ST_10_pushButton_5)
        self.ST_Q10_horizontal_question_lyt.addLayout(self.ST_Q10_horizontal_selection_lyt)
        self.verticalLayout_11.addLayout(self.ST_Q10_horizontal_question_lyt)
        self.ST_Tab_gridLayout.addWidget(self.ST_widget, 0, 0, 1, 1)
        self.Stress_tabWidget.addTab(self.ST_Tab, "")
        self.Stress_Page_gridLayout.addWidget(self.Stress_tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Stress_Page)         